#!/usr/bin/python

""" 
    This is the code to accompany the Lesson 2 (SVM) mini-project.

    Use a SVM to identify emails from the Enron corpus by their authors:    
    Sara has label 0
    Chris has label 1
"""
    
import sys
import numpy as np
from time import time
sys.path.append("../tools/")
from email_preprocess import preprocess
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


### features_train and features_test are the features for the training
### and testing datasets, respectively
### labels_train and labels_test are the corresponding item labels
features_train, features_test, labels_train, labels_test = preprocess()

# Record time to train
t0 = time()
clf = SVC(C=10000, gamma='auto')
clf.fit(features_train, labels_train)
print("Training time: ", round(time()-t0, 3), "s")

t0= time()
pred = clf.predict(features_test)
print("Predict time: ", round(time()-t0, 3), "s")

accuracy = accuracy_score(pred, labels_test)
print("Accuracy is: ", accuracy)
